# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bros',
            field=models.ManyToManyField(to='core.BroType'),
        ),
    ]
