# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160912_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_user_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
